name: example
description: flutter_html example app.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.13.2 <4.0.0'

dependencies:
  # flutter_html: ^3.0.0
  # flutter_html_all: ^3.0.0
  flutter_html:
    path: ..
    # git:
    #   url: https://github.com/phamconganh/flutter_html
    #   ref: dev2
  # flutter_html_all:
  #   # path: ../packages/flutter_html_all
  #   git:
  #     url: https://github.com/phamconganh/flutter_html
  #     path: packages/flutter_html_all
  #     ref: dev2
  flutter:
    sdk: flutter
  material_ui: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/html5.png
    - assets/mac.svg
