name: flutter_html_all
description: All optional flutter_html widgets, bundled into a single package.
version: 3.0.0-beta.2
homepage: https://github.com/Sub6Resources/flutter_html
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  # flutter_html: ^3.0.0-beta.2
  # flutter_html_audio: ^3.0.0-beta.2
  # flutter_html_iframe: ^3.0.0-beta.2
  # flutter_html_math: ^3.0.0-beta.2
  # flutter_html_svg: ^3.0.0-beta.2
  # flutter_html_table: ^3.0.0-beta.2
  # flutter_html_video: ^3.0.0-beta.2
  flutter_html:
    git:
      url: https://github.com/phamconganh/flutter_html
      ref: dev2
  flutter_html_audio:
    git:
      url: https://github.com/phamconganh/flutter_html
      path: packages/flutter_html_audio
      ref: dev2
  flutter_html_iframe:
    git:
      url: https://github.com/phamconganh/flutter_html
      path: packages/flutter_html_iframe
      ref: dev2
  flutter_html_math:
    git:
      url: https://github.com/phamconganh/flutter_html
      path: packages/flutter_html_math
      ref: dev2
  flutter_html_svg:
    git:
      url: https://github.com/phamconganh/flutter_html
      path: packages/flutter_html_svg
      ref: dev2
  flutter_html_table:
    git:
      url: https://github.com/phamconganh/flutter_html
      path: packages/flutter_html_table
      ref: dev2
  flutter_html_video:
    git:
      url: https://github.com/phamconganh/flutter_html
      path: packages/flutter_html_video
      ref: dev2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

funding:
  - https://opencollective.com/flutter_html

topics:
  - html
  - css
  - widgets
  - layout
  - flutter_html
