name: flutter_html_material_ui
description: This extension package allows the <details> tag to be rendered using the flutter_html package
version: 3.0.0
homepage: https://github.com/Sub6Resources/flutter_html
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.13.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_html: ^3.0.0
  flutter_html:
    git:
      url: https://github.com/phamconganh/flutter_html
      ref: dev2
  material_ui: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

funding:
  - https://github.com/sponsors/Sub6Resources

topics:
  - html
  - css
  - audio
  - layout
