name: flutter_html_math
description: This extension package allows the <math> tag to be rendered using the flutter_html package
version: 3.0.0
homepage: https://github.com/Sub6Resources/flutter_html
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.13.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  # flutter_html: ^3.0.0
  flutter_html:
    git:
      url: https://github.com/phamconganh/flutter_html
      ref: dev2
  flutter_math_fork: '>=0.7.0 <1.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

funding:
  - https://github.com/sponsors/Sub6Resources

topics:
  - html
  - latex
  - math
  - tex
