name: flutter_html_audio
description: This extension package allows the <audio> tag to be rendered using the flutter_html package
version: 3.0.0-beta.2+1
homepage: https://github.com/Sub6Resources/flutter_html
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  # flutter_html: ^3.0.0-beta.2
  flutter_html:
    git:
      url: https://github.com/phamconganh/flutter_html
      ref: dev2
  video_player: '>=2.8.6 <3.0.0'
  # chewie: '>=1.8.1 <2.0.0'
  chewie_audio: '>=1.5.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

funding:
  - https://opencollective.com/flutter_html

topics:
  - html
  - css
  - audio
  - layout
  - flutter_html
